apiVersion: apps/v1
kind: ReplicaSet # 파드를 만듬
metadata:
  name: apahce-pod-replica # 파드의 이름
  # labels:
  #   app: apahce-replica
spec:
  replicas: 10 # 0 으로 변경하여 삭제
  selector:
    matchLabels:
      app: apahce-replica # template.metadata.labels.[key] 와 맞아야함.
  # 어떤 형태로 만들 것인가.
  template:
    metadata:
      labels:
        app: apahce-replica # selector.matchLabels.[key] 와 맞아야함.
    spec:
      containers:
        - name: ac
          image: httpd:2.4
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/local/apache2/htdocs
              name: hostpath-volume # 일치해야함
              readOnly: true
      volumes:
        - name: hostpath-volume # 일치해야함
          hostPath:
            path: /root/k8s-test/hostpath
            type: Directory 
      nodeName: master # 노드 명시
      

# volumes.name.hostPath.path를 
# containers.name.volumeMounts.mountPath로 임포트함

# hostpath는 노드에 종속되므로
# 노드간 hostpath는 연결되지 않는다

# 따라서
# 배포할 노드를 정해주어야 함.

# nodeName: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodename
