kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wp-pvc
spec:
  selector:
    matchLabels:
      type: local-wp
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi 
