apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: myns
  name: use-pod
rules:
- apiGroups: [""] # "" indicates the core API group , "" <- core API group
  resources: ["pods"]
  verbs: ["create", "get", "watch", "list"]

