apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: use-pod
  namespace: myns
subjects:
- kind: ServiceAccount
  name: myuser # "name" is case sensitive
  namespace: myns
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: use-pod # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io