apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: use-all-service
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["services"]
  verbs: ["get","list"]