apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx  # 'name'을 'app'으로 수정하여 Service의 Selector와 일치시킴
spec:
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
    - containerPort: 80
  