apiVersion: v1
kind: Pod
metadata:
  name: apache
  labels:
    name: apache
spec:
  containers:
  - name: apache
    image: httpd:2.4
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 80
