apiVersion: v1
kind: Pod
metadata:
  name: apache
  labels:
    name: apache
spec:
  containers:
  - name: apache
    image: httpd:2.4
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 80
    volumeMounts:
    - mountPath: /usr/local/apache2/htdocs
      name: hostpath-volume # 일치해야함
      readOnly: true
  volumes:
  - name: hostpath-volume # 일치해야함
    hostPath:
      path: /root/k8s-test/hostpath
      type: Directory 

# volumes.name.hostPath.path를 
# containers.name.volumeMounts.mountPath로 임포트함