kind: PersistentVolume
apiVersion: v1
metadata:
  name: wp-pv
  labels:
    type: local-wp
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/root/k8s-test/wordpress/hostpath/wordpress"
