apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - image: wordpress
          name: wordpress
          env:
          - name: WORDPRESS_DB_HOST
            value: mysql:3306
          - name: WORDPRESS_DB_NAME
            # value: mydb
            valueFrom:
              configMapKeyRef:
                key: mysql_user_db
                name: mysqlconfig
          - name: WORDPRESS_DB_USER
            # value: myuser
            valueFrom:
              configMapKeyRef:
                key: mysql_user_id
                name: mysqlconfig
          - name: WORDPRESS_DB_PASSWORD
            # value: userpass
            valueFrom:
              secretKeyRef:
                key: mysql_user_pwd
                name: mysqlsecret
          ports:
            - containerPort: 80
              name: wordpress
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: wp-pvc
